#!/bin/bash
# places all necessary files for delivery of working application to a third
# party, into "../code_delivery"
#

CODE_DELIV_DIR='../code_delivery'
IMG_DIR=''${CODE_DELIV_DIR}'/images'
IMG='images/model_white_bg.png'
FILES='*.py run pydc1394 calibration pipeline_modules admin_modules simulator'
EXCLUDES='\*.pyc \*.swp'
ARCHIVE=''${CODE_DELIV_DIR}'/code.zip'
ARCHIVE_TARGET=''${CODE_DELIV_DIR}'/*'
DELIV_DIR='../interim_delivery'
REPORT='../report/report.pdf'

if [ -d $CODE_DELIV_DIR ]; then
    rm -r $CODE_DELIV_DIR
fi

mkdir $CODE_DELIV_DIR
mkdir $IMG_DIR

for i in $FILES
    do
        cp -r $i $CODE_DELIV_DIR
    done

for i in $IMG
    do
        cp $IMG $IMG_DIR
    done

zip -r $ARCHIVE $ARCHIVE_TARGET -x $EXCLUDES

if [ -d $DELIV_DIR ]; then
    rm -r $DELIV_DIR
fi
mkdir $DELIV_DIR

mv $ARCHIVE $DELIV_DIR
if [ ! -f $REPORT ]; then
    cd ../report
    make
    cd ../src
fi
cp $REPORT $DELIV_DIR

rm -r $CODE_DELIV_DIR

echo '--> Done!'
cd $DELIV_DIR
echo '--> Items for delivery are now in directory:'
pwd
echo ''
cd ../src
